# Generated by Django 5.1 on 2024-08-10 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('telephone', models.CharField(max_length=15)),
                ('adresse', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Habitat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('avenue', models.CharField(max_length=255)),
                ('quartier', models.CharField(max_length=255)),
                ('commune', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponibilite', models.BooleanField(default=True)),
                ('images', models.ImageField(upload_to='habitats/')),
            ],
        ),
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('telephone', models.CharField(max_length=15)),
                ('adresse', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='formateur',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='formateur',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='formateur',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='suivre',
            name='formation',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='suivre',
            name='participant',
        ),
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.client')),
                ('habitat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.habitat')),
            ],
        ),
        migrations.AddField(
            model_name='habitat',
            name='idProprietaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.proprietaire'),
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.client')),
                ('habitat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.habitat')),
            ],
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
        migrations.DeleteModel(
            name='Formateur',
        ),
        migrations.DeleteModel(
            name='Formation',
        ),
        migrations.DeleteModel(
            name='Paiement',
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
        migrations.DeleteModel(
            name='Suivre',
        ),
    ]
