# Generated by Django 5.1 on 2024-08-18 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_client_habitat_proprietaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitat',
            name='image_to',
            field=models.ImageField(default='static/image/maison-deux.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='habitat',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
