# Generated by Django 5.1 on 2024-08-18 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_habitat_image_to_alter_habitat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitat',
            name='image_on',
            field=models.ImageField(default='static/image/maison-deux.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='habitat',
            name='localisation',
            field=models.CharField(default='https://maps.app.goo.gl/cxDy3WQex4ibrVXG9', max_length=255),
        ),
    ]
